### ISSUE TITLE
Modern Fortran - C in first column treated as a comment on second line

### ISSUE THREAD

**Issue by rmcdermo** [textmate/fortran.tmbundle#10]
With latest bundle I get the following behavior. In the cases below, the first line is highlighted correctly but the second line is treated as a comment.

C(1,1) = DOT_PRODUCT(E1,SS)
C(1,2) = DOT_PRODUCT(E1,PP)

C(1,1) = DOT_PRODUCT(E1,SS)
[skip a line]
C(1,2) = DOT_PRODUCT(E1,PP)

**Comment by infininight** [comment]
I get all those lines as comments. The fortran language has always been hard to accomplish because it is not really defined in a single place. When I look up fortran comments I get that any line beginning with a C should be a comment, can you point to something that gives explanations of what makes it a comment/not?

**Comment by rmcdermo** [comment]
C or c is a comment in f77.  In modern fortran (f90+) a comment is started with !

**Comment by anowacki** [comment]
I can confirm this behaviour.  The following valid modern Fortran program will write the letter 'a' to stdout.  The second line assigns 'a' to the variable c, but with the current bundle, this line will be erroneously formatted as a comment:

``` Fortran
character c
c = 'a'
write(*,*) c
end
```

The problem arises because of the `Fortran - Punchcard` rule 'comment.line.c.fortran', which captures anything as a comment when the first character of the line is c or C.  This is the correct behaviour for Fortran 77, but not Fortran 90+, however this rule in inherited by `Fortran - Modern` (`include = 'source.fortran'`).  There should be some rule in `Fortran - Modern` which removes or changes 'comment.line.c.fortran' for modern Fortran to amend that.  I'm afraid as a Fortran user, my understanding of the way TextMate bundles work is too limited to effect the change myself!

**Comment by infininight** [comment]
Corrected in 96e540061b8bfaa5426a7dfd979651bd8a92d462, thanks!
